/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberosgrupo47.Vistas;

import bomberosgrupo47.accesoADatos.BomberoData;
import bomberosgrupo47.accesoADatos.BrigadaData;
import bomberosgrupo47.entidades.Bombero;
import bomberosgrupo47.entidades.Brigada;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.TemporalQueries.localDate;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author usuario
 */
public class BomberoVista extends javax.swing.JInternalFrame {

    private BomberoData bomdata = new BomberoData ();
    private Bombero bomberoActual=null;
    
    
    
    /**
     * Creates new form BomberoVista
     */
    public BomberoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtidbombero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jrestado = new javax.swing.JRadioButton();
        jtdni = new javax.swing.JTextField();
        jtnombreapellido = new javax.swing.JTextField();
        jtnrocelular = new javax.swing.JTextField();
        jtcodbrigada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1300, 640));

        jLabel1.setText("idBombero");

        jLabel2.setText("Dni");

        jLabel3.setText("Nombre&Apellido");

        jLabel4.setText("FechaNacimiento");

        jLabel5.setText("NroCelular");

        jLabel6.setText("CodigoBrigada");

        jtidbombero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidbomberoActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado");

        jrestado.setText("Activo");
        jrestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrestadoActionPerformed(evt);
            }
        });

        jtcodbrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcodbrigadaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver-al-menu-principal.jpeg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Nuevo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Alta, Baja y Modificacion de Bomberos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtnombreapellido, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton5)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jtcodbrigada)
                                                        .addComponent(jrestado)
                                                        .addComponent(jtidbombero)))
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton3)))
                                        .addComponent(jtnrocelular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton1)))
                                .addContainerGap(290, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtidbombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtnombreapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtnrocelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jtcodbrigada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jrestado))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrestadoActionPerformed

    private void jtidbomberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidbomberoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtidbomberoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // limpiar campos de carga de Bomberos
        jDate.setDate(null);
        jtidbombero.setText("");
        jtdni.setText("");
        jtnombreapellido.setText("");
       
        jtnrocelular.setText("");
        jtcodbrigada.setText("");
        jrestado.setSelected(true);
        bomberoActual = null;
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // guardar o actualizar datos de los Bomberos
        
        try{
            
            int idBombero = Integer.parseInt(jtidbombero.getText());
            //int idBombero = 0;
            
            int idBom = Integer.parseInt(jtidbombero.getText());
            int dni=Integer.parseInt(jtdni.getText());
            String nomape=jtnombreapellido.getText();
            
            java.util.Date sfecha = jDate.getDate();
            LocalDate fechaNac = sfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            //Date date = Date.from(sin.getFechaSiniestro().atStartOfDay(ZoneId.systemDefault()).toInstant());
            //    jdFecha.setDate(date);
            
            String nrocel=jtnrocelular.getText();
            int codbrig=Integer.parseInt(jtcodbrigada.getText());
            BrigadaData bd=new BrigadaData();
            Brigada bri=bd.buscarBrigada(codbrig);
            
            boolean est=jrestado.isSelected();

//            if (idBom==1||dni==null) {
//                JOptionPane.showMessageDialog(this," * campos requeridos ");
//                return ;
//            }
            


            if (bomberoActual==null) {
               
if (bd.BrigadaEspacio(codbrig)==false) {
                 JOptionPane.showMessageDialog(this," la brigada esta completa no se puede agregar un nuevo bombero ");
                 
                    return;
            }
                bomberoActual=new Bombero(idBom,dni,nomape,fechaNac,nrocel,bri);
                bomdata.guardarBombero(bomberoActual);
            }else {
                bomberoActual.setIdBombero(idBom);
                bomberoActual.setDni(dni);
                bomberoActual.setNombreApellido(nomape);
                
                bomberoActual.setFechaNac(fechaNac);
                
                //bomberoActual.setActivo(est);
                bomdata.modificarBombero(bomberoActual);

            }

        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "error debe ingresar un Codigo Valido");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // buscar un bombero
                     
        try {
            int code=Integer.parseInt(jtidbombero.getText());
            int idBombero = code;

            bomberoActual=bomdata.buscarBombero(idBombero);

            if (bomberoActual!=null) {

                jtdni.setText(bomberoActual.getDni()+"");
                jtnombreapellido.setText(bomberoActual.getNombreApellido());
                LocalDate lc = bomberoActual.getFechaNac();
                //LocalDate date=java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                //Date date = Date.from(sin.getFechaSiniestro().atStartOfDay(ZoneId.systemDefault()).toInstant());
                //jdFecha.setDate(date);
                jDate.setDate(java.sql.Date.valueOf(lc));
                jtnrocelular.setText(bomberoActual.getCelular());
                jtcodbrigada.setText(bomberoActual.getBrigada().getCodBrigada()+"");
                
//                jrestado.setSelected(bomberoActual.isActivo());
            //}else{
              //  JOptionPane.showMessageDialog(this, "intente otra vez");
            }

        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Debe ingresar un Nro");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtcodbrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcodbrigadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcodbrigadaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Eliminar un Bombero de la Basede Datos
        
        if (bomberoActual!=null) {
        
            bomdata.bajaBombero(bomberoActual.getIdBombero());
            bomberoActual=null;
            jtidbombero.setText("");
            
            jtdni.setText("");
            jtnombreapellido.setText("");
            
            jtnrocelular.setText("");
            jtcodbrigada.setText("");
            jrestado.setSelected(true);
            
        }else{
            JOptionPane.showMessageDialog(this, "No Selecciono ningun Bombero para Eliminar");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jrestado;
    private javax.swing.JTextField jtcodbrigada;
    private javax.swing.JTextField jtdni;
    private javax.swing.JTextField jtidbombero;
    private javax.swing.JTextField jtnombreapellido;
    private javax.swing.JTextField jtnrocelular;
    // End of variables declaration//GEN-END:variables
}
